// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChineseItem struct {
	ID        int32
	Character string
	Pinyin    string
	Meaning   string
	CreatedAt pgtype.Timestamptz
	LessonID  pgtype.Int4
	Audio     pgtype.Text
	Pitch     []float32
}

type Feedback struct {
	ID        int32
	UserID    int32
	ItemID    int32
	Feedback  string
	CreatedAt pgtype.Timestamptz
}

type Lesson struct {
	ID          int32
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID        int32
	DeviceID  string
	CreatedAt pgtype.Timestamptz
}
