// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousUser = `-- name: CreateAnonymousUser :one
INSERT INTO users (device_id, created_at)
VALUES ($1, $2)
RETURNING id, device_id, created_at
`

type CreateAnonymousUserParams struct {
	DeviceID  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAnonymousUser(ctx context.Context, arg CreateAnonymousUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAnonymousUser, arg.DeviceID, arg.CreatedAt)
	var i User
	err := row.Scan(&i.ID, &i.DeviceID, &i.CreatedAt)
	return i, err
}

const createChineseItem = `-- name: CreateChineseItem :one
INSERT INTO chinese_items (character, pinyin, meaning, lesson_id)
VALUES ($1, $2, $3, $4)
RETURNING id, character, pinyin, meaning, created_at, lesson_id, audio, pitch
`

type CreateChineseItemParams struct {
	Character string
	Pinyin    string
	Meaning   string
	LessonID  pgtype.Int4
}

func (q *Queries) CreateChineseItem(ctx context.Context, arg CreateChineseItemParams) (ChineseItem, error) {
	row := q.db.QueryRow(ctx, createChineseItem,
		arg.Character,
		arg.Pinyin,
		arg.Meaning,
		arg.LessonID,
	)
	var i ChineseItem
	err := row.Scan(
		&i.ID,
		&i.Character,
		&i.Pinyin,
		&i.Meaning,
		&i.CreatedAt,
		&i.LessonID,
		&i.Audio,
		&i.Pitch,
	)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedbacks (user_id, item_id, feedback)
VALUES ($1, $2, $3)
RETURNING id, user_id, item_id, feedback, created_at
`

type CreateFeedbackParams struct {
	UserID   int32
	ItemID   int32
	Feedback string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback, arg.UserID, arg.ItemID, arg.Feedback)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at
`

type CreateLessonParams struct {
	Title       string
	Description pgtype.Text
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson, arg.Title, arg.Description)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getChineseItemByID = `-- name: GetChineseItemByID :one
SELECT id, character, pinyin, meaning, created_at, lesson_id, audio, pitch FROM chinese_items WHERE id = $1
`

func (q *Queries) GetChineseItemByID(ctx context.Context, id int32) (ChineseItem, error) {
	row := q.db.QueryRow(ctx, getChineseItemByID, id)
	var i ChineseItem
	err := row.Scan(
		&i.ID,
		&i.Character,
		&i.Pinyin,
		&i.Meaning,
		&i.CreatedAt,
		&i.LessonID,
		&i.Audio,
		&i.Pitch,
	)
	return i, err
}

const getChineseItems = `-- name: GetChineseItems :many
SELECT id, character, pinyin, meaning, created_at, lesson_id, audio, pitch FROM chinese_items
ORDER BY created_at
`

func (q *Queries) GetChineseItems(ctx context.Context) ([]ChineseItem, error) {
	rows, err := q.db.Query(ctx, getChineseItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChineseItem
	for rows.Next() {
		var i ChineseItem
		if err := rows.Scan(
			&i.ID,
			&i.Character,
			&i.Pinyin,
			&i.Meaning,
			&i.CreatedAt,
			&i.LessonID,
			&i.Audio,
			&i.Pitch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChineseItemsByLesson = `-- name: GetChineseItemsByLesson :many
SELECT id, character, pinyin, meaning, created_at, lesson_id, audio, pitch FROM chinese_items
WHERE lesson_id = $1
ORDER BY created_at
`

func (q *Queries) GetChineseItemsByLesson(ctx context.Context, lessonID pgtype.Int4) ([]ChineseItem, error) {
	rows, err := q.db.Query(ctx, getChineseItemsByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChineseItem
	for rows.Next() {
		var i ChineseItem
		if err := rows.Scan(
			&i.ID,
			&i.Character,
			&i.Pinyin,
			&i.Meaning,
			&i.CreatedAt,
			&i.LessonID,
			&i.Audio,
			&i.Pitch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbacks = `-- name: GetFeedbacks :many
SELECT feedback, created_at FROM feedbacks
WHERE user_id = $1 AND item_id = $2
ORDER BY created_at DESC
`

type GetFeedbacksParams struct {
	UserID int32
	ItemID int32
}

type GetFeedbacksRow struct {
	Feedback  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFeedbacks(ctx context.Context, arg GetFeedbacksParams) ([]GetFeedbacksRow, error) {
	rows, err := q.db.Query(ctx, getFeedbacks, arg.UserID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedbacksRow
	for rows.Next() {
		var i GetFeedbacksRow
		if err := rows.Scan(&i.Feedback, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbacksByUserAndItem = `-- name: GetFeedbacksByUserAndItem :many
SELECT id, user_id, item_id, feedback, created_at FROM feedbacks
WHERE user_id = $1 AND item_id = $2
ORDER BY created_at DESC
`

type GetFeedbacksByUserAndItemParams struct {
	UserID int32
	ItemID int32
}

func (q *Queries) GetFeedbacksByUserAndItem(ctx context.Context, arg GetFeedbacksByUserAndItemParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbacksByUserAndItem, arg.UserID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Feedback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessons = `-- name: GetLessons :many
SELECT id, title, description, created_at FROM lessons
ORDER BY created_at
`

func (q *Queries) GetLessons(ctx context.Context) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, getLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, device_id, created_at FROM users 
WHERE device_id = $1 
LIMIT 1
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(&i.ID, &i.DeviceID, &i.CreatedAt)
	return i, err
}

const updateChineseItemAudio = `-- name: UpdateChineseItemAudio :one
UPDATE chinese_items
SET audio = $2,
    pitch = $3
WHERE id = $1
RETURNING id, character, pinyin, meaning, created_at, lesson_id, audio, pitch
`

type UpdateChineseItemAudioParams struct {
	ID    int32
	Audio pgtype.Text
	Pitch []float32
}

func (q *Queries) UpdateChineseItemAudio(ctx context.Context, arg UpdateChineseItemAudioParams) (ChineseItem, error) {
	row := q.db.QueryRow(ctx, updateChineseItemAudio, arg.ID, arg.Audio, arg.Pitch)
	var i ChineseItem
	err := row.Scan(
		&i.ID,
		&i.Character,
		&i.Pinyin,
		&i.Meaning,
		&i.CreatedAt,
		&i.LessonID,
		&i.Audio,
		&i.Pitch,
	)
	return i, err
}
